In [344]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math as mth

In [345]:
data = pd.read_excel("DATA IN YEARS/2021.xlsx")
days = np.arange(1,366)

In [346]:
data.index = days
# data.index

In [347]:
data.head(2)

,Day,Month,Year,SolRadiation (MJ/m²/day),TempMin (°C),TempMax (°C),RelHumMin (%),RelHumMax (%)
1,1,1,2021,13.9038,23.5,34.0,25,94
2,2,1,2021,10.6242,25.0,32.5,40,94

In [348]:
# data.info()

In [349]:
data["TempMax (°C)"][364]

32.1

In [350]:
data.head(1)

,Day,Month,Year,SolRadiation (MJ/m²/day),TempMin (°C),TempMax (°C),RelHumMin (%),RelHumMax (%)
1,1,1,2021,13.9038,23.5,34.0,25,94

In [351]:
import math
okay = []
def model():
    for i in days:
        eq1 = 1+0.033*np.cos((((2*22*i)/7)/365))     #equation 1
#         eq2 = 23.45 * np.sin(360*((284+i)/365))    #equation 2
        eq2 = 0.409 * np.sin((((2*i*22)/7)/365) - 1.39) 
        eq3 = np.arccos(-np.tan(7.3775)*np.tan(eq2)) 
        eq4 = (((24*3600)/(22/7))*(0.1367*eq1)*((np.cos(7.3775) * np.cos(eq2)*np.sin(eq3)) + (((22*eq3)/7)*np.sin(7.3775)*np.sin(eq2))/180))
        tmax = 0.6108*np.exp(17.27*data["TempMax (°C)"][i]/(data["TempMax (°C)"][i] + 237.3))
        tmin = 0.6108*np.exp(17.27*data["TempMin (°C)"][i]/(data["TempMin (°C)"][i] + 237.3))
        eq5 = ((tmin*((data["RelHumMax (%)"][i]/100)) + (tmax*(data["RelHumMin (%)"][i])/100))/2 )
        eq6 = 0.75+(2* (np.power(np.exp(10),-5)))*0.230
#         eq7 = 0.00000000000004903 *(((np.power((data["TempMax (°C)"][i] + 273.16), 4) + np.power((data["TempMin (°C)"][i] + 273.16), 4))/2)*(((0.34-(0.14 * math.sqrt(eq5))))* ((1.35*i)/eq6)-0.35))
        eq7 = 0.000000004903 *((np.power((data["TempMax (°C)"][i] + 273.16), 4) + np.power((data["TempMin (°C)"][i] + 273.16), 4))/2)*(((0.34-(0.14 * eq5)))* ((1.35*data["SolRadiation (MJ/m²/day)"][i])/eq6)-0.35) 
        eq8 = data["SolRadiation (MJ/m²/day)"][i] - eq7
        eq9 = (1-0.3)* data["SolRadiation (MJ/m²/day)"][i]
        okay.append(eq9)

In [352]:
model()

In [362]:
alllm = []
for i in okay:
    if i < 1:
        alllm.append("deficit")
    else:
        alllm.append("surplus")

In [364]:
len(okay)

730

In [365]:
data["net radiation name"] = alllm
data["net radiation"] = okay
# data["net radiation name"].unique()

ValueError: Length of values (730) does not match length of index (365)

In [359]:
# okay = []
# def model():
#     for i in days:
#         eq1 = 1+0.033*np.cos((((2*22*i)/7)/365))     #equation 1
# #         eq2 = 23.45 * np.sin(360*((284+i)/365))    #equation 2
#         eq2 = 0.409 * np.sin((((2*i*22)/7)/365) - 1.39) 
#         eq3 = np.arccos(-np.tan(7.3775)*np.tan(eq2))    #equation 3
#         eq4 = (((24*3600)/(22/7))*(0.1367*eq1)*((np.cos(7.3775) * np.cos(eq2)*np.sin(eq3)) + (((22*eq3)/7)*np.sin(7.3775)*np.sin(eq2))/180)) #(np.cos(7.3775)*np.cos(eq2)*np.sin(eq3) + ((eq3*22/7)/180)*np.sin(7.3775)*np.sin(eq2))
#         tmax = 0.6108*np.exp(17.27*data["TempMax (°C)"][i]/(data["TempMax (°C)"][i] + 237.3))
#         tmin = 0.6108*np.exp(17.27*data["TempMin (°C)"][i]/(data["TempMin (°C)"][i] + 237.3))
#         eq5 = ((tmin*((data["RelHumMax (%)"][i]/100)) + (tmax*(data["RelHumMin (%)"][i])/100))/2 )
#         eq6 = 0.75+(2* (np.power(np.exp(10),-5)))*0.230
#         eq7 = 40.03 *((np.power((data["RelHumMax (%)"][i] + 273.16), 4) + np.power((data["TempMin (°C)"][i] + 273.16), 4))/2)*(((0.34-(0.14 * eq5)))* ((1.35*i)/eq6)-0.35)  ###(0.34-0.14) (1.35*(data["SolRadiation (MJ/m²/day)"][i]/eq6) - 0.35)
        
#         eq8 = data["SolRadiation (MJ/m²/day)"][i] - eq7
#         eq9 = (1-0.3)* data["SolRadiation (MJ/m²/day)"][i]
#         okay.append(eq8 * i)

In [355]:
model()

In [356]:
alllm = []
for i in okay:
    if i < 1:
        alllm.append("deficit")
    else:
        alllm.append("surplus")

In [357]:
data["net radiation name"] = alllm
data["net radiation"] = okay
data["net radiation name"].unique()

ValueError: Length of values (730) does not match length of index (365)

In [189]:
data

,Day,Month,Year,SolRadiation (MJ/m²/day),TempMin (°C),TempMax (°C),RelHumMin (%),RelHumMax (%),net radiation name,net radiation
1,1,1,2021,13.9038,23.5,34.0,25,94,surplus,1.289110e+11
2,2,1,2021,10.6242,25.0,32.5,40,94,surplus,3.855588e+11
3,3,1,2021,10.0185,25.0,34.0,43,96,surplus,8.395440e+11
4,4,1,2021,12.3033,25.0,35.1,29,91,surplus,3.698371e+11
5,5,1,2021,14.5065,23.0,29.5,38,95,deficit,-1.083354e+11
...,...,...,...,...,...,...,...,...,...,...
361,27,12,2021,16.0407,23.0,34.0,5,100,deficit,-1.579091e+16
362,28,12,2021,15.2298,24.0,33.0,25,90,deficit,-7.546006e+15
363,29,12,2021,10.6476,23.2,31.0,38,97,deficit,-3.380122e+15
364,30,12,2021,15.1722,22.0,32.1,5,96,deficit,-1.811503e+16
365,31,12,2021,12.6912,22.1,32.0,29,95,deficit,-8.233460e+15

In [190]:
allequ10 = []
allequ12 = []
text = []
surplus =  []
deficit =  []
number = 0

for ai in days:
    j = ai + 1
    i = ai
    m = np.where(j==1,1,(ai/(ai-1)))
    
    equ10 = (data["net radiation"][ai]/data["net radiation"][ai]-1)
#         equ12 = np.where(ai==1,ai/ai,(ai/(ai-1)))
    equ12 = np.where(ai==1,1,(data["net radiation"][ai]/(data["net radiation"][ai]-1)))

    equ13 = np.power(equ12,ai)
    equ14 = data["net radiation"][ai]
    equ16 = ai* equ12 
    equ17 =  np.where(j==1,1,(j* i)/(1+(j * i) - (j +1)))
    equ18 = 1 - equ17
    equ19 = equ17 + equ18
    equ20 = (1/equ17) + (1/equ18)
#         print(equ20)
    surplus.append(equ17)
    deficit.append(equ18)

<ipython-input-190-1d7474617bf5>:11: RuntimeWarning: divide by zero encountered in long_scalars
  m = np.where(j==1,1,(ai/(ai-1)))
<ipython-input-190-1d7474617bf5>:20: RuntimeWarning: divide by zero encountered in long_scalars
  equ17 =  np.where(j==1,1,(j* i)/(1+(j * i) - (j +1)))
<ipython-input-190-1d7474617bf5>:22: RuntimeWarning: invalid value encountered in add
  equ19 = equ17 + equ18

In [191]:
data["surplus"] = surplus
data["deficit"] = deficit
data

,Day,Month,Year,SolRadiation (MJ/m²/day),TempMin (°C),TempMax (°C),RelHumMin (%),RelHumMax (%),net radiation name,net radiation,surplus,deficit
1,1,1,2021,13.9038,23.5,34.0,25,94,surplus,1.289110e+11,inf,-inf
2,2,1,2021,10.6242,25.0,32.5,40,94,surplus,3.855588e+11,2.0,-1.000000
3,3,1,2021,10.0185,25.0,34.0,43,96,surplus,8.395440e+11,1.5,-0.500000
4,4,1,2021,12.3033,25.0,35.1,29,91,surplus,3.698371e+11,1.3333333333333333,-0.333333
5,5,1,2021,14.5065,23.0,29.5,38,95,deficit,-1.083354e+11,1.25,-0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...
361,27,12,2021,16.0407,23.0,34.0,5,100,deficit,-1.579091e+16,1.0027777777777778,-0.002778
362,28,12,2021,15.2298,24.0,33.0,25,90,deficit,-7.546006e+15,1.002770083102493,-0.002770
363,29,12,2021,10.6476,23.2,31.0,38,97,deficit,-3.380122e+15,1.0027624309392265,-0.002762
364,30,12,2021,15.1722,22.0,32.1,5,96,deficit,-1.811503e+16,1.002754820936639,-0.002755
365,31,12,2021,12.6912,22.1,32.0,29,95,deficit,-8.233460e+15,1.0027472527472527,-0.002747

In [192]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 365 entries, 1 to 365
Data columns (total 12 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Day                       365 non-null    int64
 1   Month                     365 non-null    int64
 2   Year                      365 non-null    int64
 3   SolRadiation (MJ/m²/day)  365 non-null    float64
 4   TempMin (°C)              365 non-null    float64
 5   TempMax (°C)              365 non-null    float64
 6   RelHumMin (%)             365 non-null    int64
 7   RelHumMax (%)             365 non-null    int64
 8   net radiation name        365 non-null    object
 9   net radiation             365 non-null    float64
 10  surplus                   365 non-null    object
 11  deficit                   365 non-null    float64
dtypes: float64(5), int64(5), object(2)
memory usage: 47.1+ KB

In [193]:
data.to_csv("NEW DATA/2021.csv")